name: Deploy Node.js to GCP
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
          PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          REGION: ${{secrets.GCP_REGION}}
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}


        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Set up Google Cloud SDK
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{secrets.GCP_CREDENTIALS}}

            - uses: google-github-actions/setup-gcloud@v2
              with:
                version: '>= 363.0.0'

            - name: Configure Docker for GCR
              run: |
                gcloud auth configure-docker $REGION-docker.pkg.dev

            - name: Build and push Docker image
              run: |
                docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME ./backend
                docker push $REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME

            - name: Terraform Init & Apply
              working-directory: ./infra
              run: |
                terraform init
                terraform apply -auto-approve \
                  -var="project_id=$PROJECT_ID" \
                  -var="region=$REGION" \
                  -var="image_name=$IMAGE_NAME"
